### ISSUE TITLE
`deft_funnel_main` fails for unconstrained problems

### ISSUE THREAD

**Issue by jbect** [phrsampaio/deft-funnel#2]
It seems that `deft_funnel_main` doesn't like unconstrained problems.

I am trying to optimize this test function:
```matlab
function y = goldsteinprice (x)

x1 = x(1);
x2 = x(2);

x1x1 = x1 .^ 2;
x2x2 = x2 .^ 2;
x1x2 = x1 .* x2;

A1 = (x1 + x2 + 1) .^ 2;
A2 = 19 - 14*x1 + 3*x1x1 - 14*x2 + 6*x1x2 + 3*x2x2;
A  = 1 + A1 .* A2;  % 4th degree polynomial

B1 = (2*x1 - 3*x2) .^ 2;
B2 = 18 - 32*x1 + 12*x1x1 + 48*x2 - 36*x1x2 + 27*x2x2;
B  = 30 + B1 .* B2;  % 4th degree polynomial

y = A .* B;  % 8th degree polynomial

end
```

Here is my test script:
```matlab
x0 = [0 0];
n = 2;

% Stuff for constraints
nb_cons_c = 0;
nb_cons_h = 0;
ls = [];
us = [];

% Bounds
lx = [-2 -2];
ux = [+2 +2];

% Functions
f = @goldsteinprice;
c = [];
h = [];
dev_f = [];
dev_h = [];

[best_sol, best_feval, best_indicators, best_iterate, total_eval,           ...
    nb_local_searches, fL] = deft_funnel_multistart(f, c, h, dev_f, dev_h,  ...
    n, nb_cons_c, nb_cons_h, 'lxbounds', lx, 'uxbounds', ux);
```

The script fails with the following error:
```
Error using  * 
Incorrect dimensions for matrix multiplication. Check that the number of columns in the first matrix matches the number of
rows in the second matrix. To perform elementwise multiplication, use '.*'.

Error in deft_funnel_main (line 611)
    Jsd = iterate.z_s + models.derivatives.J_s * d;

Error in deft_funnel (line 474)
    deft_funnel_main(f, c, h, dev_f, dev_h, nit, nitold, sample_set,        ...

Error in deft_funnel_multistart (line 400)
                    deft_funnel(f, c, h, dev_f, dev_h, x0,                  ...

Error in run_test (line 22)
    nb_local_searches, fL] = deft_funnel_multistart(f, c, h, dev_f, dev_h,  ...
```

Here is the full log:
[run_test.log](https://github.com/phrsampaio/deft-funnel/files/4180481/run_test.log)

**Comment by phrsampaio** [comment]
DEFT-FUNNEL is designed only for constrained problems where `nb_cons_c>0` or `nb_cons_h>0`. Unconstrained problems and bound-constrained problems (where the bounds are the only constraints) are not handled by the algorithm.

**Comment by jbect** [comment]
Ah ok...  Then an error message saying so would be nice :wink:

**Comment by jbect** [comment]
@phrsampaio what happens if I include a phony constraint which is always satisfied?

Formally, this makes it possible to run DEFT-FUNNEL on a bound-constrained problem, right?

I mean: I understand that DEFT-FUNNEL does not currently handle bound-constrained problems, but is it a fundamental limitation of the algorithm or simply a temporary limitation of the code as it is written ?

**Comment by phrsampaio** [comment]
It might work, but I would rather use the BOBYQA algorithm from Powell or any other solver for bound-constrained problems. BOBYQA also employs underdetermined quadratic models and is available in different programing languages.

DEFT-FUNNEL is a SQP method, which means that it is an improved application of Netwon's method to the KKT conditions of the problem. Without constraints, there is no point in using a SQP method.

**Comment by phrsampaio** [comment]
> Ah ok... Then an error message saying so would be nice 😉

I agree :)
